version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:

      POSTGRES_DB: "booking_db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "root"

    ports:
      - "5435:5432"

  web:
      build:
        context: .
      ports:
        - "4000:4000"
      env_file:
      - .env
      depends_on:
      - postgres

